//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFSOAPClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Distributor", Namespace="http://schemas.datacontract.org/2004/07/WCFSOAPService.Model")]
    [System.SerializableAttribute()]
    public partial class Distributor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BODS_FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid BODS_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte BODS_StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BODS_FullName {
            get {
                return this.BODS_FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BODS_FullNameField, value) != true)) {
                    this.BODS_FullNameField = value;
                    this.RaisePropertyChanged("BODS_FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BODS_Id {
            get {
                return this.BODS_IdField;
            }
            set {
                if ((this.BODS_IdField.Equals(value) != true)) {
                    this.BODS_IdField = value;
                    this.RaisePropertyChanged("BODS_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte BODS_Status {
            get {
                return this.BODS_StatusField;
            }
            set {
                if ((this.BODS_StatusField.Equals(value) != true)) {
                    this.BODS_StatusField = value;
                    this.RaisePropertyChanged("BODS_Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDistributorService")]
    public interface IDistributorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributorService/GetAllDistributors", ReplyAction="http://tempuri.org/IDistributorService/GetAllDistributorsResponse")]
        WCFSOAPClient.ServiceReference1.Distributor[] GetAllDistributors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributorService/GetAllDistributors", ReplyAction="http://tempuri.org/IDistributorService/GetAllDistributorsResponse")]
        System.Threading.Tasks.Task<WCFSOAPClient.ServiceReference1.Distributor[]> GetAllDistributorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributorService/Add", ReplyAction="http://tempuri.org/IDistributorService/AddResponse")]
        WCFSOAPClient.ServiceReference1.Distributor Add(WCFSOAPClient.ServiceReference1.Distributor e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributorService/Add", ReplyAction="http://tempuri.org/IDistributorService/AddResponse")]
        System.Threading.Tasks.Task<WCFSOAPClient.ServiceReference1.Distributor> AddAsync(WCFSOAPClient.ServiceReference1.Distributor e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributorService/Edit", ReplyAction="http://tempuri.org/IDistributorService/EditResponse")]
        WCFSOAPClient.ServiceReference1.Distributor[] Edit(WCFSOAPClient.ServiceReference1.Distributor[] e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributorService/Edit", ReplyAction="http://tempuri.org/IDistributorService/EditResponse")]
        System.Threading.Tasks.Task<WCFSOAPClient.ServiceReference1.Distributor[]> EditAsync(WCFSOAPClient.ServiceReference1.Distributor[] e);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDistributorServiceChannel : WCFSOAPClient.ServiceReference1.IDistributorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DistributorServiceClient : System.ServiceModel.ClientBase<WCFSOAPClient.ServiceReference1.IDistributorService>, WCFSOAPClient.ServiceReference1.IDistributorService {
        
        public DistributorServiceClient() {
        }
        
        public DistributorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DistributorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFSOAPClient.ServiceReference1.Distributor[] GetAllDistributors() {
            return base.Channel.GetAllDistributors();
        }
        
        public System.Threading.Tasks.Task<WCFSOAPClient.ServiceReference1.Distributor[]> GetAllDistributorsAsync() {
            return base.Channel.GetAllDistributorsAsync();
        }
        
        public WCFSOAPClient.ServiceReference1.Distributor Add(WCFSOAPClient.ServiceReference1.Distributor e) {
            return base.Channel.Add(e);
        }
        
        public System.Threading.Tasks.Task<WCFSOAPClient.ServiceReference1.Distributor> AddAsync(WCFSOAPClient.ServiceReference1.Distributor e) {
            return base.Channel.AddAsync(e);
        }
        
        public WCFSOAPClient.ServiceReference1.Distributor[] Edit(WCFSOAPClient.ServiceReference1.Distributor[] e) {
            return base.Channel.Edit(e);
        }
        
        public System.Threading.Tasks.Task<WCFSOAPClient.ServiceReference1.Distributor[]> EditAsync(WCFSOAPClient.ServiceReference1.Distributor[] e) {
            return base.Channel.EditAsync(e);
        }
    }
}
